---
- name: "Ensure sudo package is installed"
  apt:
    name: sudo
    state: present
  become: true

- name: "Allow or Deny '{{ ansible_user }}' to execute pct exec via sudo without password"
  community.general.sudoers:
    name: "pct-all"
    user: "{{ ansible_user }}"
    commands:
      - "/usr/sbin/pct exec *"
    nopassword: true
    state: "{{ 'present' if allowed_lxc_ids | length == 0 else 'absent' }}"
    validation: "required"

- name: "Allow '{{ ansible_user }}' to execute pct exec via sudo without password for specific LXC IDs"
  community.general.sudoers:
    name: "pct-ids"
    user: "{{ ansible_user }}"
    commands:
      - "/usr/sbin/pct exec {{ item }} *"
    nopassword: true
    state: "{{ 'present' if allowed_lxc_ids | length > 0 else 'absent' }}"
    validation: "required"
    loop: "{{ allowed_lxc_ids }}"
...
