---
- name: "Disable subscription warning in proxmoxlib.js (PBS 3.3.x)"
  replace:
    path: "/usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js"
    regexp: '\.data\.status\.toLowerCase\(\) !== .active.\) \{'
    replace: ".data.status.toLowerCase() !== 'active' && false) {"
    backup: true
  when: pbs_version is version('3.3', '>=') and pbs_version is version('3.4', '<')
  notify: "Restart PBS Proxy"

- name: "Disable subscription warning in proxmoxlib.js (PBS 3.4.x, 4.x)"
  replace:
    path: "/usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js"
    regexp: 'res\.data\.status\.toLowerCase\(\) !== ''active''\n(\s*)\) \{\n'
    replace: |
      (res.data.status.toLowerCase() !== 'active' && false)
      \1) {
    backup: true
  when: pbs_version is version('3.4', '>=') and pbs_version is version('5.0', '<')
  notify: "Restart PBS Proxy"
...
