---
- name: "Disable subscription warning in proxmoxlib.js (PBS 3.x)"
  replace:
    path: "/usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js"
    regexp: '\.data\.status\.toLowerCase\(\) !== .active.\) \{'
    replace: ".data.status.toLowerCase() !== 'active' && false) {"
    backup: true
  when: pbs_version is version('3.3', '>=') and pbs_version is version('4.0', '<')
  notify: "Restart PBS Proxy"
...
